[package]
name = "rapido"
version = "0.1.0"
authors = ["David Bryson <daveb@miceda.org>"]
edition = "2018"
license = "Apache-2.0"
keywords = ["tendermint", "blockchain"]
description = "A Rust framework for building Tendermint applications"

[dependencies]
abci = "0.6.2"
base64 = "0.10.1"
exonum-merkledb = "0.12.0"
exonum-crypto = "0.12.0"
failure = "0.1.5"
bincode = "1.2.0"
protobuf = "2.8.1"
serde = "1.0.101"
serde_derive = "1.0.101"

[build-dependencies]
protobuf-codegen-pure = "2.8.1"
