[package]
name = "rapido-client"
version = "0.1.0"
authors = ["Dave Bryson <daveb@miceda.org>"]
edition = "2018"

[dependencies]
hex = "0.4.0"
base64 = "0.10.1"
json = "0.12.0"
reqwest = "0.9.22"
url = "2.1.0"
